apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
  namespace: production
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myprodacr3.azurecr.io/myapp:e41917a
        ports:
        - containerPort: 5001

  strategy:
    canary:
      stableService: myapp-stable
      canaryService: myapp-canary
      trafficRouting:
        nginx:
          stableIngress: myapp
      steps:
      - setWeight: 10
      - pause: {duration: 60}
      - setWeight: 25
      - pause: {duration: 60}
      - setWeight: 50
      - pause: {duration: 60}
      - setWeight: 100
