image:
  repository: myprodacr3.azurecr.io/myapp
  tag: "dbcd292"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 5001

ingress:
  enabled: true
  host: "myapp.example.com"

canary:
  enabled: true
  steps:
    - weight: 10
      pauseSeconds: 60
    - weight: 25
      pauseSeconds: 60
    - weight: 50
      pauseSeconds: 60
    - weight: 100
