image:
  repository: myprodacr3.azurecr.io/myapp
  tag: "1b9228a"
  pullPolicy: IfNotPresent

blueGreen:
  active: "green"    # change to green during deployment

service:
  port: 80
  targetPort: 5001

ingress:
  enabled: true
  host: "myapp.example.com"
