apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: prod
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/app-password"
        objectType: "secretsmanager"
